openapi: 3.0.0
info:
  title: Movies API
  description: API for managing movies, including retrieving, creating, and getting details of movies.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local server

paths:
  /movies/readAll:
    get:
      summary: Get all movies
      description: Retrieve a list of all movies.
      tags:
        - Movies
      responses:
        '200':
          description: A list of movies.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
        '500':
          description: Internal server error.
  /movies/create:
    post:
      summary: Create a new movie
      description: Create a movie with title, release year, director, duration, synopsis, and poster URL.
      tags:
        - Movies
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieCreateRequest'
      responses:
        '201':
          description: The created movie.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieCreateResponse'
        '500':
          description: Internal server error.

  /movies/{id}:
    get:
      summary: Get a movie by ID
      description: Retrieve details of a single movie by its ID.
      tags:
        - Movies
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the movie to retrieve.
          schema:
            type: integer
      responses:
        '200':
          description: The requested movie.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
        '404':
          description: Movie not found.
        '500':
          description: Internal server error.

components:
  schemas:
    Movie:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        release_year:
          type: integer
        director:
          type: string
        duration_minutes:
          type: integer
        synopsis:
          type: string
        poster_url:
          type: string
          format: uri
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    MovieCreateRequest:
      type: object
      properties:
        title:
          type: string
        release_year:
          type: integer
        director:
          type: string
        duration_minutes:
          type: integer
        synopsis:
          type: string
        poster_url:
          type: string
          format: uri
      required:
        - title
        - release_year
        - director
        - duration_minutes

    MovieCreateResponse:
      type: object
      properties:
        newMovie:
          $ref: '#/components/schemas/Movie'